# goreleaser.yml
# Build customization
project_name: tsuru
builds:
- main: ./tsuru
  binary: tsuru
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
    - 386
    - arm64
  ignore:
    - goos: darwin
      goarch: 386
    - goos: windows
      goarch: arm64
  env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}


# Archive customization
archives:
- name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
  format: tar.gz
  replacements:
    darwin: macOS
  format_overrides:
    - goos: windows
      format: zip
  files:
    - misc/bash-completion
    - misc/zsh-completion

release:
  extra_files:
    - glob: dist/metadata.json
    - glob: dist/CHANGELOG.md

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  prerelease: auto
